# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Flat.create([
  { :name => "Nice house", :bedroom_count => 2, :address => "Alexandra Grove, London, UK", :latitude => 51.6121, :longitude => -0.18248, :created_at => "2013-05-14 12:54:05", :updated_at => "2013-05-14 12:54:05" },
  { :name => "Manor house room", :bedroom_count => 1, :address => "Manor House, UK", :latitude => 51.5707, :longitude => -0.09609, :created_at => "2013-05-14 14:09:58", :updated_at => "2013-05-14 19:23:31" },
  { :name => "Shoreditch house", :bedroom_count => 3, :address => "Shoreditch, London, UK", :latitude => 51.5285, :longitude => -0.084728, :created_at => "2013-05-14 14:16:08", :updated_at => "2013-05-14 19:46:09" },
  { :name => "Wimbledon house", :bedroom_count => 5, :address => "Wimbledon, UK", :latitude => 51.4183, :longitude => -0.220629, :created_at => "2013-05-14 14:16:42", :updated_at => "2013-05-14 14:16:42" },
  { :name => "Beach house", :bedroom_count => 3, :address => "Brighton, UK", :latitude => 50.8225, :longitude => -0.137163, :created_at => "2013-05-14 19:48:29", :updated_at => "2013-05-14 19:48:29" }
], :without_protection => true )


